# Generated by Django 5.2.1 on 2025-05-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='type',
            field=models.CharField(choices=[('roadmap', 'Roadmap'), ('course', 'Course')], max_length=20),
        ),
    ]
