# Generated by Django 5.2.1 on 2025-05-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
